services:
  - type: web
    name: superset
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: superset-db
          property: connectionString
      - key: SUPERSET_SECRET_KEY
        value: change-this-secret-key
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_FIRSTNAME
        value: Superset
      - key: ADMIN_LASTNAME
        value: Admin

databases:
  - name: superset-db
    engine: postgresql
    plan: free
